app/core/views.py
from flask import Blueprint, render_template

core_bp = Blueprint('core', __name__, template_folder='../templates')


@core_bp.route("/")
@core_bp.route("/home")
def home():
    """
    Renders the home page template.

    Returns:
        Response: The rendered "home.html" template.
    """
    return render_template("home.html")

app/groups/views.py
from functools import wraps
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from app.core.models import Core
from app.groups.models import Group
from app.auth.models import User


groups_bp = Blueprint('groups', __name__, template_folder='../templates')


# Docstrings written by GPT4o and edited by myself.
def must_be_tutor_or_admin(f):
    """
    Decorator to ensure that the current user has either 'Tutor' or 'Admin'
    role.

    This decorator is used to restrict access to certain view functions only to
    users with specific roles. If the current user does not have the 'Tutor' or
    'Admin' role, it flashes an unauthorized access message and redirects the
    user to their profile page. This is useful for protecting endpoints that
    should be accessible only by users in these roles.

    Args:
        f (function): The view function to wrap.

    Returns:
        function: The wrapped function with added role-based access control.
    """
    @wraps(f)
    def wrapper(*args, **kwargs):
        if current_user.role not in ["Admin", "Tutor"]:
            flash("You are not authorized to do this.", "error")
            return redirect(
                url_for('auth.profile', username=current_user.username)
                )
        return f(*args, **kwargs)
    return wrapper


@groups_bp.route("/get_groups")
@login_required
@must_be_tutor_or_admin
def get_groups():
    """
    Renders the groups template with a list of groups filtered by the current
    user's role and username.

    This function retrieves the list of groups from the database based on the
    current user's role and username. It then renders the groups template,
    passing the filtered list of groups to the template.

    Returns:
        Response: Renders the groups.html template with the list of groups
        filtered by the user's role and username.
    """
    groups = Group.get_groups_by_role(current_user.role, current_user.username)

    return render_template("groups.html", groups=groups)


@groups_bp.route("/add_group", methods=["GET", "POST"])
@login_required
@must_be_tutor_or_admin
def add_group():
    """
    Handles the creation of a new group and renders the add_group template.

    On a GET request, this function renders the add_group template with the
    necessary data for creating a group.
    On a POST request, it inserts a new group into the database using the
    provided form data, flashes a success message to the user, and redirects to
    the get_groups view.

    Returns:
        Response:
            - On GET: Renders the add_group.html template with the list of
            providers and levels.
            - On POST: Redirects to the get_groups view after successfully
            creating a group.
    """
    if request.method == "POST":
        tutor = current_user.username
        provider = request.form.get("provider")
        level = request.form.get("level")
        year = request.form.get("year")
        weekday = request.form.get("weekday")
        Group.insert_group(tutor, provider, level, year, weekday)
        flash("Group Created")
        return redirect(url_for('groups.get_groups'))

    providers = Core.get_providers()
    levels = Core.get_levels()

    return render_template(
        "add_group.html",
        providers=providers,
        levels=levels
        )


@groups_bp.route("/add_student", defaults={"username": None}, methods=['POST'])
@groups_bp.route("/add_student/<username>", methods=['POST'])
@login_required
@must_be_tutor_or_admin
def add_student(username):
    """
    Adds a student to a specific group based on form submissions and redirects
    to the group management view.

    This function is accessible via POST request where it processes the
    inclusion of a specified student into a designated group. If a username is
    provided, the function attempts to find the user and, subsequently, the
    group ID from the form data. If both the user and the group are validated,
    the student is added to the group's students list in the database. The
    function handles different scenarios such as missing user, missing group
    ID, or unspecified student by flashing appropriate messages and redirecting
    accordingly.

    Args:
        username (str, optional): The username of the student to be added to
        the group.

    Returns:
        Response: Redirects to the groups management view, flashing success or
        error messages based on the outcome of the operation.
    """
    if username:
        user_search = User.find_by_username(username, True)
        if user_search is None:
            flash("User Not Found")
            return redirect(url_for("auth.view_users"))
        group_id = request.form.get("group_id")
        if group_id:
            Group.add_student_to_group(group_id, username)
            flash("Student Added")
        else:
            flash("Group ID not provided", "error")

        return redirect(url_for("groups.get_groups"))
    else:
        flash("Student Not Specified")
        return redirect(url_for("auth.view_users"))


@groups_bp.route("/remove_student", defaults={
    "group_id": None, "username": None
    })
@groups_bp.route("/remove_student/<group_id>", defaults={"username": None})
@groups_bp.route("/remove_student/<group_id>/<username>")
@login_required
@must_be_tutor_or_admin
def remove_student(group_id, username):
    """
    Removes a student from a specific group based on the provided group ID and
    student username.

    This function is responsible for removing a specified student from a
    designated group's student list. It validates the presence of both a group
    ID and a student username. If both are provided, it proceeds to remove the
    student from the group. A success message is flashed to the user upon
    successful removal. If either the group ID or username is missing, it
    flashes an error message indicating that both pieces of information are
    necessary.

    Args:
        group_id (str, optional): The ID of the group from which the student is
        to be removed. Required for the operation to proceed.
        username (str, optional): The username of the student to be removed
        from the group. Required for the operation to proceed.

    Returns:
        Response: Redirects to the groups management view, flashing messages
        based on the success or failure of the student removal operation.
    """
    if group_id and username:
        Group.remove_student(group_id, username)
        flash("Student Removed")
        return redirect(url_for('groups.get_groups'))
    else:
        flash("Group and Student Not Specified")
        return redirect(url_for("groups.get_groups"))


@groups_bp.route("/edit_group", defaults={"group_id": None})
@groups_bp.route("/edit_group/<group_id>", methods=["GET", "POST"])
@login_required
@must_be_tutor_or_admin
def edit_group(group_id):
    """
    Manages the editing of an existing group's details.

    This function handles both GET and POST requests for a specific group based
    on the group ID provided.
    - On a GET request, it retrieves the group's details and displays them in a
    form for editing.
    - On a POST request, it updates the group with the data provided in the
    form and then redirects to the group management view.

    If no group ID is provided, or if the specified group cannot be found, it
    flashes an appropriate error message and redirects to the group listing
    page.

    Args:
        group_id (str, optional): The ID of the group to be edited. If not
        provided, the function will return to the group listing.

    Returns:
        Response:
            - On GET requests: Renders the 'edit_group.html' template with the
            current group details, providers, and levels available for
            selection.
            - On POST requests: Saves the changes and redirects to the group
            management view with a success message.
            - On missing or not found group_id: Redirects to the group
            management view with an error message.
    """
    if group_id:
        group = Group.get_group_by_id(group_id)
        if group is None:
            flash("No Group Found")
            return redirect(url_for("groups.get_groups"))
        if request.method == "POST":
            tutor = current_user.username
            provider = request.form.get("provider")
            level = request.form.get("level")
            year = request.form.get("year")
            weekday = request.form.get("weekday")
            students = group["students"]
            Group.edit_group(
                group_id, tutor, provider, level, year, weekday, students
                )
            flash("Group Edited")
            return redirect(url_for('groups.get_groups'))

        providers = Core.get_providers()
        levels = Core.get_levels()

        return render_template(
            "edit_group.html",
            group=group,
            providers=providers,
            levels=levels)

    else:
        flash("Group Not Specified")
        return redirect(url_for("groups.get_groups"))


@groups_bp.route("/delete_group", defaults={"group_id": None})
@groups_bp.route("/delete_group/<group_id>")
@login_required
@must_be_tutor_or_admin
def delete_group(group_id):
    """
    Deletes a specific group from the database and redirects to the group
    management view.

    This function checks if a valid group ID is provided and verifies if the
    group exists. If the group exists, it proceeds with deletion using the
    Group.delete_group method. Upon successful deletion, a success message is
    flashed. If no group is found or if no group ID is provided, it flashes an
    error message accordingly.

    Args:
        group_id (str, optional): The unique identifier of the group to be

app/posts/views.py
from functools import wraps
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user, login_required
from app.core.models import Core
from app.posts.models import Post
from app.groups.models import Group


posts_bp = Blueprint('posts', __name__, template_folder='../templates')


# Docstrings written by GPT4o and edited by myself.
@posts_bp.route("/get_posts", methods=["GET", "POST"])
def get_posts():
    """
    Displays a list of posts, either all or filtered by specified criteria.

    On a GET request, this function retrieves all available posts along with
    associated categories and groups that are relevant based on the current
    user's role and username. It renders the posts template to display these
    posts.

    On a POST request, it processes form data to filter posts based on selected
    categories and groups. It then retrieves and renders the posts template
    with this filtered list of posts.

    Returns:
        Response: Renders the 'posts.html' template with variables for the list
        of posts, categories, and groups available to the user, as well as any
        active query parameters used for filtering.
    """
    categories = Core.get_categories()
    posts, query = Post.get_list(None, None)
    if current_user.is_authenticated:
        groups = Group.get_groups_by_role(
            current_user.role, current_user.username)
    else:
        groups = []

    if request.method == "POST":
        category = request.form.get("category")
        group_id = request.form.get("group")
        posts, query = Post.get_list(category, group_id)

    return render_template(
        "posts.html",
        posts=posts,
        categories=categories,
        groups=groups,
        query=query
        )


@posts_bp.route("/make_post", methods=["GET", "POST"])
@login_required
def make_post():
    """
    Handles the creation of a new post and renders the make_post template.

    On a GET request, this function renders the 'make_post.html' template with
    the necessary data for creating a post, including a list of categories and
    groups relevant to the current user's role and username. This provides a
    form for users to submit a new post.

    On a POST request, it captures the form data to insert a new post into the
    database, including the username, selected category, group ID, title, and
    description of the post. Upon successful insertion, it flashes a success
    message and redirects the user to the 'get_posts' view to view all posts.

    Returns:
        Response:
            - Renders the 'make_post.html' template with options for categories
            and groups on a GET request.
            - Redirects to the 'get_posts' view with a success message on a
            POST request, indicating successful post creation.
    """
    if request.method == "POST":
        username = current_user.username
        category = request.form.get("category")
        group_id = request.form.get("group")
        title = request.form.get("title")
        description = request.form.get("description")
        Post.insert_post(username, category, group_id, title, description)
        flash("Post Published")
        return redirect(url_for('posts.get_posts'))

    groups = Group.get_groups_by_role(current_user.role, current_user.username)
    categories = Core.get_categories()
    return render_template(
        "make_post.html",
        categories=categories,
        groups=groups
        )


def user_owns_post_or_admin(f):
    """
    Decorator to ensure that the current user either owns the post or has
    'Admin' privileges.

    This decorator is designed to restrict access to certain view functions
    that manipulate a post. It checks if the current user is either the owner
    of the post (based on the username associated with the post) or has an
    'Admin' role. If neither condition is met, it flashes an unauthorized
    access error message and redirects the user to their profile page. If the
    specified post does not exist or no post_id is provided, it redirects to
    the posts listing page with an error message.

    Args:
        f (function): The view function to which the decorator is applied.

    Returns:
        function: The wrapped function with added authorization checks, or
        redirections if checks fail.
    """
    @wraps(f)
    def wrapper(*args, **kwargs):
        post_id = kwargs.get('post_id')
        post = Post.find_by_id(post_id)
        if post is None:
            flash("Post not specified.", "error")
            return redirect(url_for('posts.get_posts'))
        if (current_user.username != post['username'] and
                current_user.role != 'Admin'):
            flash("You are not authorized to do this.", "error")
            return redirect(
                url_for('auth.profile', username=current_user.username))
        return f(*args, **kwargs)
    return wrapper


@posts_bp.route("/edit_post", defaults={"post_id": None})
@posts_bp.route("/edit_post/<post_id>", methods=["GET", "POST"])
@login_required
@user_owns_post_or_admin
def edit_post(post_id):
    """
    Handles the editing of an existing post and renders the edit_post template.

    On a GET request, this function retrieves the post by its ID and renders
    the 'edit_post.html' template with the post's current data, including
    available categories and groups based on the user's role.

    On a POST request, it captures updated post details from the form data
    (title, description, category, and group) and updates the post in the
    database. After updating, it flashes a success message and redirects the
    user to the 'get_posts' view to see all posts.

    Args:
        post_id (str, optional): The ID of the post to be edited. If not
        provided, a GET request leads to the posts listing.

    Returns:
        Response:
            - On GET: Renders the 'edit_post.html' template with the post's
            details and options for categories and groups.
            - On POST: Updates the post and redirects to 'get_posts' view with
            a success message.
    """
    if request.method == "POST":
        username = current_user.username
        category = request.form.get("category")
        group_id = request.form.get("group")
        title = request.form.get("title")
        description = request.form.get("description")
        Post.update_post(
            post_id, username, category, group_id, title, description
            )
        flash("Post Updated")
        return redirect(url_for('posts.get_posts'))

    groups = Group.get_groups_by_role(current_user.role, current_user.username)
    categories = Core.get_categories()
    post = Post.find_by_id(post_id)
    return render_template(
        "edit_post.html",
        post=post,
        groups=groups,
        categories=categories
        )


@posts_bp.route("/delete_post", defaults={"post_id": None})
@posts_bp.route("/delete_post/<post_id>")
@login_required
@user_owns_post_or_admin
def delete_post(post_id):
    """
    Deletes a post from the database and redirects to the get_posts view.

    This function deletes the specified question from the database. It then
    flashes a success message to the user and redirects to the get_posts view.

    Args:
        post_id (str): The ID of the post to be deleted.

    Returns:
        Response: Redirects to the get_posts view after deleting the post.
    """
    Post.delete_post(post_id)
    flash("Post Deleted")
    return redirect(url_for("posts.get_posts"))

app/templates/edit_comment.html
{% extends "base.html" %}

{% set active_page = "posts" %}

{% block content %}

<!-- Post card template -->
<div class="card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <p><a class="highlight1" href="{{ url_for('auth.profile', username=post.username) }}">{{
          post.username
          }}</a> <em class="secondary-text">{{
          post.time_ago }}</em>
      </p>
      <p class="category highlight2"><em>{{ post.category }}</em></p>
    </div>
    <p class="card-title">{{ post.title }}</p>
    <p class="secondary-text">{{ post.description }}</p>
  </div>
  <div class="card-footer d-flex justify-content-between">
    <a href="{{ url_for('comments.view_comments', post_id=post._id) }}" class="card-link">View comments ({{
      post.comment_count
      }})</a>
    {% if current_user.username == post.username or current_user.role == 'Admin' %}
    <div>
      <a href="{{ url_for('posts.edit_post', post_id=post._id) }}" class="card-link">Edit</a>
      <a href="#" class="card-link" data-bs-toggle="modal" data-bs-target="#{{ post._id }}">Delete</a>

      <!-- Delete post modal -->
      <div class="modal fade" id="{{ post._id }}" tabindex="-1" aria-labelledby="modalLabel{{ post._id }}"
        aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="modalLabel{{ post._id }}">Are you sure?</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Changes cannot be undone!</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
              <a href="{{ url_for('posts.delete_post', post_id=post._id) }}" class="btn btn-outline-danger">Confirm</a>
            </div>
          </div>
        </div>
      </div>

    </div>
    {% endif %}
  </div>
</div>

{% for comment in comments %}
{% if comment["_id"] == comment_id %}
<!-- Edit comment card -->
<div class="card">
  <div class="card-body">
    <form method="POST" action="{{ url_for('comments.edit_comment', comment_id=comment._id) }}" class="mb-0">
      <div class="container">
        <div class="row">
          <div class="col-sm-9 mb-3">
            <textarea class="form-control" id="text" name="text" rows="3" maxlength="500" placeholder="Add comment"
              aria-label="Text box to edit comment" required>{{ comment.text }}</textarea>
          </div>
          <div class="col-sm-3 d-flex justify-content-center align-items-center">
            <button type="submit" class="btn btn-outline-warning">Save Edit</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% else %}
<!-- Normal comment cards -->
<div class="container">
  <div class="row">
    {% if current_user.username == comment.username %}
    <div class="col-1"></div>
    {% endif %}
    <div class="col-11">
      <div class="card">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <p><a class="highlight1" href="{{ url_for('auth.profile', username=comment.username) }}">{{ comment.username
                }}</a>
              <em class="secondary-text">{{ comment.time_ago }}</em>
            </p>
            {% if current_user.username == post.username or current_user.role == 'Admin' %}
            <div>
              <a href="{{ url_for('comments.edit_comment', comment_id=comment._id) }}" class="card-link">Edit</a>
              <a href="#" class="card-link" data-bs-toggle="modal" data-bs-target="#{{ comment._id }}">Delete</a>

              <!-- Delete comment modal -->
              <div class="modal fade" id="{{ comment._id }}" tabindex="-1" aria-labelledby="modalLabel{{ comment._id }}"
                aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h1 class="modal-title fs-5" id="modalLabel{{ comment._id }}">Are you sure?</h1>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <p>Changes cannot be undone!</p>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                      <a href="{{ url_for('comments.delete_comment', comment_id=comment._id) }}"
                        class="btn btn-outline-danger">Confirm</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}
          </div>

          <p class="primary-text">{{ comment.text }}</p>

        </div>
      </div>
    </div>
    {% if current_user.username != comment.username %}
    <div class="col-1"></div>
    {% endif %}
  </div>
</div>

{% endif %}

{% endfor %}

{% endblock %}

app/templates/forgot_password.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Confirm Email to Reset Password</h1>

<div class="container d-flex justify-content-center">
  <form method="POST" action="{{ url_for('auth.forgot_password') }}">
    <div class="container">
      <div class="row mb-3">
        <div class="col-12">
          <label for="email">Enter Email:</label>
          <input type="email" class="form-control" id="email" name="email" maxlength="50" required>
        </div>
      </div>
      <div class="d-flex justify-content-center">
        <button class="btn btn-outline-warning btn-lg" type="submit">Send</button>
      </div>
    </div>
  </form>

</div>

{% endblock %}

app/templates/groups.html
{% extends 'base.html' %}

{% set active_page = "groups" %}

{% block content %}
<header>
  <div class="text-center">
    <h1>Groups</h1>
    <a href="{{ url_for('groups.add_group') }}" class="btn btn-outline-warning btn-lg">Add Group</a>
  </div>
</header>

{% if not groups %}

<div class="d-flex flex-column justify-content-center text-center">
  <p class="secondary-text">No groups created</p>
</div>

{% endif %}

{% for group in groups %}

<div class="card">
  <div class="card-body">
    <div class="container">
      <div class="row">
        <div class="col-12 col-md-8 col-xxl-9">
          <div class="row">
            <div class="col-md-8">
              <div class="row">
                <div class="col-12 col-xxl-6">
                  <p class="card-text secondary-text">Tutor: <span class="primary-text">{{ group.tutor }}</span></p>
                </div>
                <div class="col-12 col-xxl-6">
                  <p class="card-text secondary-text">Weekday: <span class="primary-text">{{ group.weekday }}</span></p>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-12 col-xxl-6">
                  <p class="card-text secondary-text">Level: <span class="card-value primary-text">{{
                      group.level}}</span>
                  </p>
                </div>
                <div class="col-12 col-xxl-6">
                  <p class="card-text secondary-text">Year: <span class="card-value primary-text">{{ group.year
                      }}</span>
                  </p>
                </div>
              </div>
            </div>
            <div class="col-12">
              <p class="card-text secondary-text">Provider: <span class="card-value primary-text">{{
                  group.provider}}</span></p>
            </div>
          </div>

        </div>
        <div class="col-12 col-md-4 col-xxl-3">
          <div class="accordion" id="accordion{{ group._id }}">
            <div class="accordion-item">
              <h2 class="accordion-header">
                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                  data-bs-target="#collapse{{ group._id }}" aria-expanded="true"
                  aria-controls="collapse{{ group._id }}">
                  Student List
                </button>
              </h2>
              <div id="collapse{{ group._id }}" class="accordion-collapse collapse"
                data-bs-parent="accordion{{ group._id }}">
                <div class="accordion-body">
                  {% for student in group.students %}
                  <div class="d-flex justify-content-between">
                    <p>{{ student }}</p>
                    <a href="#" data-bs-toggle="modal" data-bs-target="#{{ student }}">Remove</a>

                    <!-- Modal -->
                    <div class="modal fade" id="{{ student }}" tabindex="-1"
                      aria-labelledby="deleteModalLabel{{ student }}" aria-hidden="true">
                      <div class="modal-dialog">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h1 class="modal-title fs-5" id="deleteModalLabel{{ student }}">Are you sure?</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                          </div>
                          <div class="modal-body">
                            <p>Changes cannot be undone!</p>
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn btn-outline-secondary"
                              data-bs-dismiss="modal">Cancel</button>
                            <a href="{{ url_for('groups.remove_student', group_id=group._id, username=student) }}"
                              class="btn btn-outline-danger">Confirm</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card-footer d-flex justify-content-around">
    <a href="{{ url_for('groups.edit_group', group_id=group._id) }}" class="card-link">Edit Group</a>
    <a href="#" data-bs-toggle="modal" data-bs-target="#deleteModal{{ group._id }}" class="card-link">Delete
      Group</a>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal{{ group._id }}" tabindex="-1"
      aria-labelledby="deleteModalLabel{{ group._id }}" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="deleteModalLabel{{ group._id }}">Are you sure?</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>Changes cannot be undone!</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
            <a href="{{ url_for('groups.delete_group', group_id=group._id) }}"
              class="btn btn-outline-danger">Confirm</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endfor %}

{% endblock %}

app/templates/make_post.html
{% extends 'base.html' %}

{% block content %}

<h1 class="text-center">Make Post</h1>

<div class="card">
  <div class="card-body">
    <form method="POST" action="{{ url_for('posts.make_post') }}">
      <div class="container">
        <div class="row">
          <div class="col-sm-6 mb-2">
            <label for="category" class="form-label">Category</label>
            <select id="category" name="category" class="form-select" aria-label="Default select example" required>
              <option value="" disabled selected>Choose Category</option>
              {% for category in categories %}
              <option value="{{ category.category_name }}">{{ category.category_name }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-sm-6 mb-2">
            <label for="group" class="form-label">For All or Group?</label>
            <select id="group" name="group" class="form-select" aria-label="Default select example">
              <option value="">All</option>
              {% for group in groups %}
              <option value="{{ group._id }}">{{ group.weekday }}, {{ group.provider }}, {{ group.level }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-12 mb-2">
            <label for="title" class="form-label">Title</label>
            <input type="text" class="form-control" id="title" name="title" placeholder="Max 50 characters"
              maxlength="50" required>
          </div>
          <div class="col-12 mb-2">
            <label for="description" class="form-label">Description</label>
            <textarea class="form-control" id="description" name="description" rows="3" maxlength="500"
              required></textarea>
          </div>
          <div class="col-12 d-flex justify-content-center align-items-center mt-2 mb-2">
            <button type="submit" class="btn btn-outline-warning">Submit</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>

{% endblock %}